### ISSUE TITLE
What is Site name & Key name ?

### ISSUE THREAD

**Issue by bhushankumarl** [radekg/spreedly-node#4]
https://docs.spreedly.com/basics/credentials/

As per this they are only providing Environment Key & Access secret. I didn't see anywgere Site name & Key name.

**Comment by radekg** [comment]
I'm sorry, the last commit on this project was about 5 years. I'm sure everything was fine at the time when this project has been created but the API has for sure changed a lot since then. Let me add an info regarding this project being totally obsolete.
